extends: 
  eslint: airbnb-base
  plugin: import/errors
env:
  node: true
  es6: true
rules:
  no-console: off
  import/extensions: off
  no-trailing-spaces: error
  import/no-extraneous-dependencies: error
